"""empty message

Revision ID: 554f2fafd1ee
Revises: 45e541915427
Create Date: 2020-12-06 05:49:27.103601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554f2fafd1ee'
down_revision = '45e541915427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
